[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = true

[programs.localnet]
prediction_market = "EcncSdXCTy2RnpnZPXa1VPij1tjbS6wSjrwM47vFEN9e"

[programs.devnet]
prediction_market = "EcncSdXCTy2RnpnZPXa1VPij1tjbS6wSjrwM47vFEN9e"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -t 1000000 tests/*.ts"